services:
  apiserver:
    command:
    - apiserver
    container_name: clearml-apiserver
    image: clearml/server:2
    restart: unless-stopped
    volumes:
    - ./logs:/var/log/clearml
    - ./config:/opt/clearml/config
    - ./data/fileserver:/mnt/fileserver
    depends_on:
      - redis
      - mongo
      - elasticsearch
    environment:
      CLEARML_ELASTIC_SERVICE_HOST: elasticsearch
      CLEARML_ELASTIC_SERVICE_PORT: 9200
      CLEARML_MONGODB_SERVICE_HOST: mongo
      CLEARML_MONGODB_SERVICE_PORT: 27017
      CLEARML_REDIS_SERVICE_HOST: redis
      CLEARML_REDIS_SERVICE_PORT: 6379
      CLEARML_SERVER_DEPLOYMENT_TYPE: ${CLEARML_SERVER_DEPLOYMENT_TYPE:-linux}
      CLEARML__apiserver__pre_populate__enabled: "true"
      CLEARML__apiserver__pre_populate__zip_files: "/opt/clearml/db-pre-populate"
      CLEARML__apiserver__pre_populate__artifacts_path: "/mnt/fileserver"
      CLEARML__services__async_urls_delete__enabled: "true"
      CLEARML__services__async_urls_delete__redis__host: redis
      CLEARML__services__async_urls_delete__redis__port: 6379
    ports:
    - "8008:8008"
    networks:
      - backend
  elasticsearch:
    networks:
      - backend
    container_name: clearml-elastic
    environment:
      ES_JAVA_OPTS: -Xms2g -Xmx2g -Dlog4j2.formatMsgNoLookups=true
      bootstrap.memory_lock: "true"
      cluster.name: clearml
      cluster.routing.allocation.node_initial_primaries_recoveries: "500"
      cluster.routing.allocation.disk.watermark.low: 500mb
      cluster.routing.allocation.disk.watermark.high: 500mb
      cluster.routing.allocation.disk.watermark.flood_stage: 500mb
      discovery.zen.minimum_master_nodes: "1"
      discovery.type: "single-node"
      http.compression_level: "7"
      node.name: clearml
      reindex.remote.whitelist: '*.*'
      xpack.monitoring.enabled: "false"
      xpack.security.enabled: "false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    image: elasticsearch:8.19.2
    restart: unless-stopped
    volumes:
    - ./data/elastic:/usr/share/elasticsearch/data
    - /usr/share/elasticsearch/logs
  fileserver:
    networks:
      - backend
    command:
    - fileserver
    container_name: clearml-fileserver
    image: clearml/server:2
    environment:
      CLEARML__fileserver__delete__allow_batch: "true"
    restart: unless-stopped
    volumes:
    - ./logs:/var/log/clearml
    - ./data/fileserver:/mnt/fileserver
    - ./config:/opt/clearml/config
    ports:
    - "8081:8081"
  mongo:
    networks:
      - backend
    container_name: clearml-mongo
    image: mongo:7.0.23
    restart: unless-stopped
    command: --setParameter internalQueryExecMaxBlockingSortBytes=196870912
    volumes:
    - ./data/mongo/db:/data/db
    - ./data/mongo/configdb:/data/configdb
  redis:
    networks:
      - backend
    container_name: clearml-redis
    image: redis:8.2.0
    restart: unless-stopped
    volumes:
    - ./data/redis:/data
  webserver:
    command:
    - webserver
    container_name: clearml-webserver
    environment:
      CLEARML_SERVER_DEPLOYMENT_TYPE: ${CLEARML_SERVER_DEPLOYMENT_TYPE:-linux}
    image: clearml/server:2
    restart: unless-stopped
    depends_on:
      - apiserver
    ports:
    - "8080:80"
    networks:
      - backend
  async_delete:
    depends_on:
      - apiserver
      - redis
      - mongo
      - elasticsearch
    container_name: clearml-async_delete
    image: clearml/server:2
    networks:
      - backend
    restart: unless-stopped
    environment:
      CLEARML_ELASTIC_SERVICE_HOST: elasticsearch
      CLEARML_ELASTIC_SERVICE_PORT: 9200
      CLEARML_MONGODB_SERVICE_HOST: mongo
      CLEARML_MONGODB_SERVICE_PORT: 27017
      CLEARML_REDIS_SERVICE_HOST: redis
      CLEARML_REDIS_SERVICE_PORT: 6379
      CLEARML__services__async_urls_delete__fileserver__url_prefixes: "[\"http://fileserver:8081/\"]"
    command:
    - async_delete
    volumes:
    - ./logs:/var/log/clearml
    - ./config:/opt/clearml/config
    - ./data/fileserver:/mnt/fileserver
  agent-services:
    networks:
      - backend
    container_name: clearml-agent-services
    image: clearml/clearml-agent-services:latest
    deploy:
      restart_policy:
        condition: on-failure
    privileged: true
    environment:
      CLEARML_HOST_IP: ${CLEARML_HOST_IP}
      CLEARML_WEB_HOST: ${CLEARML_WEB_HOST:-http://webserver}
      CLEARML_API_HOST: ${CLEARML_API_HOST:-http://apiserver:8008}
      CLEARML_FILES_HOST: ${CLEARML_FILES_HOST:-http://fileserver:8081}
      CLEARML_API_ACCESS_KEY: ${CLEARML_API_ACCESS_KEY:-}
      CLEARML_API_SECRET_KEY: ${CLEARML_API_SECRET_KEY:-}
      CLEARML_AGENT_GIT_USER: ${CLEARML_AGENT_GIT_USER}
      CLEARML_AGENT_GIT_PASS: ${CLEARML_AGENT_GIT_PASS}
      CLEARML_AGENT_UPDATE_VERSION: ${CLEARML_AGENT_UPDATE_VERSION:->=0.17.0}
      CLEARML_AGENT_DEFAULT_BASE_DOCKER: "ubuntu:18.04"
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-}
      AZURE_STORAGE_ACCOUNT: ${AZURE_STORAGE_ACCOUNT:-}
      AZURE_STORAGE_KEY: ${AZURE_STORAGE_KEY:-}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS:-}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/agent:/root/.clearml
    depends_on:
      - apiserver
    restart: unless-stopped

networks:
  backend:
    driver: bridge